package com.wvt.mcbewiki.others;

public class FinalValue {

    public static String wikiUrl = "https://wiki.adodoz.cn";
    public static String wikiApiUrl = "https://wiki.adodoz.cn/api.php";
    //主页文章名称
    public static String mainPageName = "Minecraft基岩版开发Wiki";
    //网页Head标签内容
    public static String headInfo = "<head>\n" +
            "<meta charset=\"UTF-8\"/>\n" +
            "<title>Minecraft基岩版开发Wiki</title>\n" +
            "<script>document.documentElement.className=\"client-js\";RLCONF={\"wgCanonicalNamespace\":\"\",\"wgCanonicalSpecialPageName\":!1,\"wgNamespaceNumber\":0,\"wgPageName\":\"Minecraft基岩版开发Wiki\",\"wgTitle\":\"Minecraft基岩版开发Wiki\",\"wgCurRevisionId\":1396,\"wgRevisionId\":1396,\"wgArticleId\":1,\"wgIsArticle\":!0,\"wgIsRedirect\":!1,\"wgAction\":\"view\",\"wgUserName\":null,\"wgUserGroups\":[\"*\"],\"wgBreakFrames\":!1,\"wgPageContentLanguage\":\"zh-cn\",\"wgPageContentModel\":\"wikitext\",\"wgSeparatorTransformTable\":[\"\",\"\"],\"wgDigitTransformTable\":[\"\",\"\"],\"wgDefaultDateFormat\":\"zh\",\"wgMonthNames\":[\"\",\"1月\",\"2月\",\"3月\",\"4月\",\"5月\",\"6月\",\"7月\",\"8月\",\"9月\",\"10月\",\"11月\",\"12月\"],\"wgMonthNamesShort\":[\"\",\"1月\",\"2月\",\"3月\",\"4月\",\"5月\",\"6月\",\"7月\",\"8月\",\"9月\",\"10月\",\"11月\",\"12月\"],\"wgRelevantPageName\":\"Minecraft基岩版开发Wiki\",\"wgRelevantArticleId\":1,\"wgRequestId\":\"87bc734a19ba9554f0631318\",\"wgCSPNonce\":!1,\"wgIsProbablyEditable\":!1,\"wgRelevantPageIsProbablyEditable\":!1,\n" +
            "\"wgRestrictionEdit\":[\"sysop\"],\"wgRestrictionMove\":[\"sysop\"],\"wgIsMainPage\":!0,\"wgMediaViewerOnClick\":!0,\"wgMediaViewerEnabledByDefault\":!0,\"wgMFMode\":\"stable\",\"wgMFAmc\":!1,\"wgMFAmcOutreachActive\":!1,\"wgMFAmcOutreachUserEligible\":!1,\"wgMFLazyLoadImages\":!0,\"wgMFDisplayWikibaseDescriptions\":{\"search\":!1,\"nearby\":!1,\"watchlist\":!1,\"tagline\":!1},\"wgMFDefaultEditor\":\"source\",\"wgMFIsPageContentModelEditable\":!0,\"wgWMESchemaEditAttemptStepOversample\":!1,\"wgPoweredByHHVM\":!1,\"wgPopupsReferencePreviews\":!1,\"wgPopupsConflictsWithNavPopupGadget\":!1,\"wgULSAcceptLanguageList\":[\"zh-cn\",\"zh\"],\"wgULSCurrentAutonym\":\"中文（中国大陆）\u200E\",\"wgVisualEditor\":{\"pageLanguageCode\":\"zh-Hans-CN\",\"pageLanguageDir\":\"ltr\",\"pageVariantFallbacks\":\"zh-cn\"},\"wgEditSubmitButtonLabelPublish\":!1,\"wgMinervaPermissions\":{\"watch\":!1,\"talk\":!1},\"wgMinervaFeatures\":{\"beta\":!1,\"mobileOptionsLink\":!0,\"categories\":!1,\"backToTop\":!1,\"shareButton\":!1,\n" +
            "\"pageIssues\":!1,\"talkAtTop\":!1,\"historyInPageActions\":!1,\"overflowSubmenu\":!1,\"tabsOnSpecials\":!1,\"personalMenu\":!1,\"mainMenuExpanded\":!1},\"wgMinervaDownloadNamespaces\":[0],\"wgMinervaMenuData\":{\"groups\":[[{\"name\":\"home\",\"components\":[{\"text\":\"首页\",\"href\":\"/Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki\",\"class\":\"mw-ui-icon mw-ui-icon-before mw-ui-icon-minerva-home\",\"data-event-name\":\"menu.home\"}]},{\"name\":\"random\",\"components\":[{\"text\":\"随机\",\"href\":\"/%E7%89%B9%E6%AE%8A:Random#/random\",\"class\":\"mw-ui-icon mw-ui-icon-before mw-ui-icon-minerva-random \",\"id\":\"randomButton\",\"data-event-name\":\"menu.random\"}]}],[{\"name\":\"auth\",\"components\":[{\"text\":\"登录\",\"href\":\"/index.php?title=%E7%89%B9%E6%AE%8A:%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95\\u0026returnto=Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki\",\"class\":\"mw-ui-icon mw-ui-icon-before mw-ui-icon-minerva-login \",\"data-event-name\":\"menu.login\"}]}],[{\"name\":\"settings\",\"components\":[{\"text\":\n" +
            "\"设置\",\"href\":\"/index.php?title=%E7%89%B9%E6%AE%8A:%E7%A7%BB%E5%8A%A8%E7%89%88%E9%80%89%E9%A1%B9\\u0026returnto=Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki\",\"class\":\"mw-ui-icon mw-ui-icon-before mw-ui-icon-minerva-settings \",\"data-event-name\":\"menu.settings\"}]}]],\"sitelinks\":[{\"name\":\"about\",\"components\":[{\"text\":\"关于Minecraft基岩版开发Wiki\",\"href\":\"/Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki:%E5%85%B3%E4%BA%8E\",\"class\":\"\"}]},{\"name\":\"disclaimers\",\"components\":[{\"text\":\"免责声明\",\"href\":\"/Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki:%E5%85%8D%E8%B4%A3%E5%A3%B0%E6%98%8E\",\"class\":\"\"}]}]}};RLSTATE={\"user.styles\":\"ready\",\"user\":\"ready\",\"user.options\":\"loading\",\"user.tokens\":\"loading\",\"skins.minerva.base.styles\":\"ready\",\"skins.minerva.content.styles\":\"ready\",\"skins.minerva.content.styles.images\":\"ready\",\"mediawiki.hlist\":\"ready\",\"mediawiki.ui.icon\":\"ready\",\"mediawiki.ui.button\":\"ready\",\"skins.minerva.icons.wikimedia\":\"ready\",\n" +
            "\"skins.minerva.icons.images\":\"ready\",\"skins.minerva.mainPage.styles\":\"ready\",\"mobile.init.styles\":\"ready\"};RLPAGEMODULES=[\"mediawiki.page.startup\",\"skins.minerva.options\",\"skins.minerva.scripts\",\"ext.gadget.site\",\"mobile.site\",\"mobile.init\",\"ext.wikimediaEvents\",\"ext.eventLogging\",\"ext.visualEditor.targetLoader\"];</script>\n" +
            "<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement(\"user.options@bpaiw\",function($,jQuery,require,module){/*@nomin*/mw.user.options.set({\"variant\":\"zh-cn\"});\n" +
            "});mw.loader.implement(\"user.tokens@tffin\",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({\"editToken\":\"+\\\\\",\"patrolToken\":\"+\\\\\",\"watchToken\":\"+\\\\\",\"csrfToken\":\"+\\\\\"});\n" +
            "});});</script>\n" +
            "<link rel=\"stylesheet\" href=\"/load.php?lang=zh-cn&amp;modules=mediawiki.hlist%7Cmediawiki.ui.button%2Cicon%7Cmobile.init.styles%7Cskins.minerva.base.styles%7Cskins.minerva.content.styles%7Cskins.minerva.content.styles.images%7Cskins.minerva.icons.images%2Cwikimedia%7Cskins.minerva.mainPage.styles&amp;only=styles&amp;skin=minerva\"/>\n" +
            "<script async=\"\" src=\"/load.php?lang=zh-cn&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=minerva&amp;target=mobile\"></script>\n" +
            "<meta name=\"generator\" content=\"MediaWiki 1.34.0\"/>\n" +
            "<meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=yes, minimum-scale=0.25, maximum-scale=5.0, width=device-width\"/>\n" +
            "<meta name=\"theme-color\" content=\"#eaecf0\"/>\n" +
            "<link rel=\"manifest\" href=\"/api.php?action=webapp-manifest\"/>\n" +
            "<link rel=\"shortcut icon\" href=\"/favicon.ico\"/>\n" +
            "<link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/opensearch_desc.php\" title=\"Minecraft基岩版开发Wiki (zh-cn)\"/>\n" +
            "<link rel=\"EditURI\" type=\"application/rsd+xml\" href=\"https://wiki.adodoz.cn/api.php?action=rsd\"/>\n" +
            "<link rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\"/>\n" +
            "<!--[if lt IE 9]><script src=\"/resources/lib/html5shiv/html5shiv.js\"></script><![endif]-->\n" +
            "</head>\n";
}
